<?php

function yuhuman_available_blood_types(): array {
	return array(
		''    => '',
		'A+'  => 'A+',
		'A-'  => 'A-',
		'B+'  => 'B+',
		'B-'  => 'B-',
		'O+'  => 'O+',
		'O-'  => 'O-',
		'AB+' => 'AB+',
		'AB-' => 'AB-',
	);
}

function yuhuman_available_blood_units(): array {
	$blood_units = array( '' => '' );

	for ( $i = 1; $i < 6; $i ++ ) {
		$blood_units[ $i ] = $i;
	}

	return $blood_units;
}

function yuhuman_available_amounts(): array {
	return array(
		''   => '',
		'1'  => '1',
		'10' => '10',
		'15' => '15',
		'20' => '20',
	);
}

function yuhuman_available_sort_by(): array {
	return array(
		''                     => '',
		'when-need-blood-asc'  => __( 'When need blood (asc)', 'yuhuman' ),
		'when-need-blood-desc' => __( 'When need blood (desc)', 'yuhuman' ),
	);
}

function yuhuman_available_districts(): array {
	return array(
		''             => '',
		'one'          => 'Bagerhat',
		'two'          => 'Bandarban',
		'three'        => 'Barguna',
		'four'         => 'Barishal',
		'five'         => 'Bhola',
		'six'          => 'Bogura',
		'seven'        => 'Brahmanbaria',
		'eight'        => 'Chandpur',
		'nine'         => 'Chapainawabganj',
		'ten'          => 'Chattogram',
		'eleven'       => 'Chuadanga',
		'twelve'       => 'Cumilla',
		'thirteen'     => 'Coxsbazar',
		'fourteen'     => 'Dhaka',
		'fifteen'      => 'Dinajpur',
		'sixteen'      => 'Faridpur',
		'seventeen'    => 'Feni',
		'eighteen'     => 'Gaibandha',
		'nineteen'     => 'Gazipur',
		'twenty'       => 'Gopalganj',
		'twenty-one'   => 'Habiganj',
		'twenty-two'   => 'Jamalpur',
		'twenty-three' => 'Jashore',
		'twenty-four'  => 'Jhalakathi',
		'twenty-five'  => 'Jhenaidah',
		'twenty-six'   => 'Joypurhat',
		'twenty-seven' => 'Khagrachhari',
		'twenty-eight' => 'Khulna',
		'twenty-nine'  => 'Kishoreganj',
		'thirty'       => 'Kurigram',
		'thirty-one'   => 'Kushtia',
		'thirty-two'   => 'Lakshmipur',
		'thirty-three' => 'Lalmonirhat',
		'thirty-four'  => 'Madaripur',
		'thirty-five'  => 'Magura',
		'thirty-six'   => 'Manikganj',
		'thirty-seven' => 'Meherpur',
		'thirty-eight' => 'Moulvibazar',
		'thirty-nine'  => 'Munshiganj',
		'forty'        => 'Mymensingh',
		'forty-one'    => 'Naogaon',
		'forty-two'    => 'Narail',
		'forty-three'  => 'Narayanganj',
		'forty-four'   => 'Narsingdi',
		'forty-five'   => 'Natore',
		'forty-six'    => 'Netrokona',
		'forty-seven'  => 'Nilphamari',
		'forty-eight'  => 'Noakhali',
		'forty-nine'   => 'Pabna',
		'fifty'        => 'Panchagarh',
		'fifty-one'    => 'Patuakhali',
		'fifty-two'    => 'Pirojpur',
		'fifty-three'  => 'Rajbari',
		'fifty-four'   => 'Rajshahi',
		'fifty-five'   => 'Rangamati',
		'fifty-six'    => 'Rangpur',
		'fifty-seven'  => 'Satkhira',
		'fifty-eight'  => 'Shariatpur',
		'fifty-nine'   => 'Sherpur',
		'sixty'        => 'Sirajganj',
		'sixty-one'    => 'Sunamganj',
		'sixty-two'    => 'Sylhet',
		'sixty-three'  => 'Tangail',
		'sixty-four'   => 'Thakurgaon',
	);
}

function yuhuman_available_upazillas(): array {
	return array(
		'one'          => array(
			''           => '',
			'Chitalmari' => 'Chitalmari',
			'Fakirhat'   => 'Fakirhat',
			'Kachua'     => 'Kachua',
			'Mollahat'   => 'Mollahat',
			'Mongla'     => 'Mongla',
			'Morrelganj' => 'Morrelganj',
			'Rampal'     => 'Rampal',
			'Sadar'      => 'Sadar',
			'Sarankhola' => 'Sarankhola',
		),
		'two'          => array(
			''               => '',
			'Alikadam'       => 'Alikadam',
			'Lama'           => 'Lama',
			'Naikhongchhari' => 'Naikhongchhari',
			'Rowangchhari'   => 'Rowangchhari',
			'Ruma'           => 'Ruma',
			'Sadar'          => 'Sadar',
			'Thanchi'        => 'Thanchi',
		),
		'three'        => array(
			''            => '',
			'Amtali'      => 'Amtali',
			'Bamna'       => 'Bamna',
			'Betagi'      => 'Betagi',
			'Pathorghata' => 'Pathorghata',
			'Sadar'       => 'Sadar',
			'Taltali'     => 'Taltali',
		),
		'four'         => array(
			''              => '',
			'Agailjhara'    => 'Agailjhara',
			'Babuganj'      => 'Babuganj',
			'Bakerganj'     => 'Bakerganj',
			'Banaripara'    => 'Banaripara',
			'Barishalsadar' => 'Barishalsadar',
			'Gournadi'      => 'Gournadi',
			'Hizla'         => 'Hizla',
			'Mehendiganj'   => 'Mehendiganj',
			'Muladi'        => 'Muladi',
			'Wazirpur'      => 'Wazirpur',
		),
		'five'         => array(
			''            => '',
			'Borhanuddin' => 'Borhanuddin',
			'Charfesson'  => 'Charfesson',
			'Doulatkhan'  => 'Doulatkhan',
			'Lalmohan'    => 'Lalmohan',
			'Monpura'     => 'Monpura',
			'Sadar'       => 'Sadar',
			'Tazumuddin'  => 'Tazumuddin',
		),
		'six'          => array(
			''            => '',
			'Adamdighi'   => 'Adamdighi',
			'Dhunot'      => 'Dhunot',
			'Dupchanchia' => 'Dupchanchia',
			'Gabtali'     => 'Gabtali',
			'Kahaloo'     => 'Kahaloo',
			'Nondigram'   => 'Nondigram',
			'Sadar'       => 'Sadar',
			'Shajahanpur' => 'Shajahanpur',
			'Shariakandi' => 'Shariakandi',
			'Sherpur'     => 'Sherpur',
			'Shibganj'    => 'Shibganj',
			'Sonatala'    => 'Sonatala',
		),
		'seven'        => array(
			''             => '',
			'Akhaura'      => 'Akhaura',
			'Ashuganj'     => 'Ashuganj',
			'Bancharampur' => 'Bancharampur',
			'Bijoynagar'   => 'Bijoynagar',
			'Kasba'        => 'Kasba',
			'Nabinagar'    => 'Nabinagar',
			'Nasirnagar'   => 'Nasirnagar',
			'Sadar'        => 'Sadar',
			'Sarail'       => 'Sarail',
		),
		'eight'        => array(
			''            => '',
			'Faridgonj'   => 'Faridgonj',
			'Haimchar'    => 'Haimchar',
			'Hajiganj'    => 'Hajiganj',
			'Kachua'      => 'Kachua',
			'Matlabnorth' => 'Matlabnorth',
			'Matlabsouth' => 'Matlabsouth',
			'Sadar'       => 'Sadar',
			'Shahrasti'   => 'Shahrasti',
		),
		'nine'         => array(
			''                     => '',
			'Bholahat'             => 'Bholahat',
			'Chapainawabganjsadar' => 'Chapainawabganjsadar',
			'Gomostapur'           => 'Gomostapur',
			'Nachol'               => 'Nachol',
			'Shibganj'             => 'Shibganj',
		),
		'ten'          => array(
			''            => '',
			'Anwara'      => 'Anwara',
			'Banshkhali'  => 'Banshkhali',
			'Boalkhali'   => 'Boalkhali',
			'Chandanaish' => 'Chandanaish',
			'Fatikchhari' => 'Fatikchhari',
			'Hathazari'   => 'Hathazari',
			'Karnafuli'   => 'Karnafuli',
			'Lohagara'    => 'Lohagara',
			'Mirsharai'   => 'Mirsharai',
			'Patiya'      => 'Patiya',
			'Rangunia'    => 'Rangunia',
			'Raozan'      => 'Raozan',
			'Sandwip'     => 'Sandwip',
			'Satkania'    => 'Satkania',
			'Sitakunda'   => 'Sitakunda',
		),
		'eleven'       => array(
			''               => '',
			'Alamdanga'      => 'Alamdanga',
			'Chuadangasadar' => 'Chuadangasadar',
			'Damurhuda'      => 'Damurhuda',
			'Jibannagar'     => 'Jibannagar',
		),
		'twelve'       => array(
			''             => '',
			'Barura'       => 'Barura',
			'Brahmanpara'  => 'Brahmanpara',
			'Burichang'    => 'Burichang',
			'Chandina'     => 'Chandina',
			'Chauddagram'  => 'Chauddagram',
			'Cumillasadar' => 'Cumillasadar',
			'Daudkandi'    => 'Daudkandi',
			'Debidwar'     => 'Debidwar',
			'Homna'        => 'Homna',
			'Laksam'       => 'Laksam',
			'Lalmai'       => 'Lalmai',
			'Meghna'       => 'Meghna',
			'Monohargonj'  => 'Monohargonj',
			'Muradnagar'   => 'Muradnagar',
			'Nangalkot'    => 'Nangalkot',
			'Sadarsouth'   => 'Sadarsouth',
			'Titas'        => 'Titas',
		),
		'thirteen'     => array(
			''            => '',
			'Chakaria'    => 'Chakaria',
			'Kutubdia'    => 'Kutubdia',
			'Moheshkhali' => 'Moheshkhali',
			'Pekua'       => 'Pekua',
			'Ramu'        => 'Ramu',
			'Sadar'       => 'Sadar',
			'Teknaf'      => 'Teknaf',
			'Ukhiya'      => 'Ukhiya',
		),
		'fourteen'     => array(
			''           => '',
			'Dhamrai'    => 'Dhamrai',
			'Dohar'      => 'Dohar',
			'Keraniganj' => 'Keraniganj',
			'Nawabganj'  => 'Nawabganj',
			'Savar'      => 'Savar',
		),
		'fifteen'      => array(
			''              => '',
			'Birampur'      => 'Birampur',
			'Birganj'       => 'Birganj',
			'Birol'         => 'Birol',
			'Bochaganj'     => 'Bochaganj',
			'Chirirbandar'  => 'Chirirbandar',
			'Dinajpursadar' => 'Dinajpursadar',
			'Fulbari'       => 'Fulbari',
			'Ghoraghat'     => 'Ghoraghat',
			'Hakimpur'      => 'Hakimpur',
			'Kaharol'       => 'Kaharol',
			'Khansama'      => 'Khansama',
			'Nawabganj'     => 'Nawabganj',
			'Parbatipur'    => 'Parbatipur',
		),
		'sixteen'      => array(
			''              => '',
			'Alfadanga'     => 'Alfadanga',
			'Bhanga'        => 'Bhanga',
			'Boalmari'      => 'Boalmari',
			'Charbhadrasan' => 'Charbhadrasan',
			'Madhukhali'    => 'Madhukhali',
			'Nagarkanda'    => 'Nagarkanda',
			'Sadar'         => 'Sadar',
			'Sadarpur'      => 'Sadarpur',
			'Saltha'        => 'Saltha',
		),
		'seventeen'    => array(
			''             => '',
			'Chhagalnaiya' => 'Chhagalnaiya',
			'Daganbhuiyan' => 'Daganbhuiyan',
			'Fulgazi'      => 'Fulgazi',
			'Parshuram'    => 'Parshuram',
			'Sadar'        => 'Sadar',
			'Sonagazi'     => 'Sonagazi',
		),
		'eighteen'     => array(
			''               => '',
			'Gaibandhasadar' => 'Gaibandhasadar',
			'Gobindaganj'    => 'Gobindaganj',
			'Palashbari'     => 'Palashbari',
			'Phulchari'      => 'Phulchari',
			'Sadullapur'     => 'Sadullapur',
			'Saghata'        => 'Saghata',
			'Sundarganj'     => 'Sundarganj',
		),
		'nineteen'     => array(
			''          => '',
			'Kaliakair' => 'Kaliakair',
			'Kaliganj'  => 'Kaliganj',
			'Kapasia'   => 'Kapasia',
			'Sadar'     => 'Sadar',
			'Sreepur'   => 'Sreepur',
		),
		'twenty'       => array(
			''           => '',
			'Kashiani'   => 'Kashiani',
			'Kotalipara' => 'Kotalipara',
			'Muksudpur'  => 'Muksudpur',
			'Sadar'      => 'Sadar',
			'Tungipara'  => 'Tungipara',
		),
		'twenty-one'   => array(
			''              => '',
			'Ajmiriganj'    => 'Ajmiriganj',
			'Bahubal'       => 'Bahubal',
			'Baniachong'    => 'Baniachong',
			'Chunarughat'   => 'Chunarughat',
			'Habiganjsadar' => 'Habiganjsadar',
			'Lakhai'        => 'Lakhai',
			'Madhabpur'     => 'Madhabpur',
			'Nabiganj'      => 'Nabiganj',
			'Shayestaganj'  => 'Shayestaganj',
		),
		'twenty-two'   => array(
			''              => '',
			'Bokshiganj'    => 'Bokshiganj',
			'Dewangonj'     => 'Dewangonj',
			'Islampur'      => 'Islampur',
			'Jamalpursadar' => 'Jamalpursadar',
			'Madarganj'     => 'Madarganj',
			'Melandah'      => 'Melandah',
			'Sarishabari'   => 'Sarishabari',
		),
		'twenty-three' => array(
			''            => '',
			'Abhaynagar'  => 'Abhaynagar',
			'Bagherpara'  => 'Bagherpara',
			'Chougachha'  => 'Chougachha',
			'Jhikargacha' => 'Jhikargacha',
			'Keshabpur'   => 'Keshabpur',
			'Manirampur'  => 'Manirampur',
			'Sadar'       => 'Sadar',
			'Sharsha'     => 'Sharsha',
		),
		'twenty-four'  => array(
			''         => '',
			'Kathalia' => 'Kathalia',
			'Nalchity' => 'Nalchity',
			'Rajapur'  => 'Rajapur',
			'Sadar'    => 'Sadar',
		),
		'twenty-five'  => array(
			''            => '',
			'Harinakundu' => 'Harinakundu',
			'Kaliganj'    => 'Kaliganj',
			'Kotchandpur' => 'Kotchandpur',
			'Moheshpur'   => 'Moheshpur',
			'Sadar'       => 'Sadar',
			'Shailkupa'   => 'Shailkupa',
		),
		'twenty-six'   => array(
			''               => '',
			'Akkelpur'       => 'Akkelpur',
			'Joypurhatsadar' => 'Joypurhatsadar',
			'Kalai'          => 'Kalai',
			'Khetlal'        => 'Khetlal',
			'Panchbibi'      => 'Panchbibi',
		),
		'twenty-seven' => array(
			''            => '',
			'Dighinala'   => 'Dighinala',
			'Guimara'     => 'Guimara',
			'Laxmichhari' => 'Laxmichhari',
			'Manikchari'  => 'Manikchari',
			'Matiranga'   => 'Matiranga',
			'Mohalchari'  => 'Mohalchari',
			'Panchari'    => 'Panchari',
			'Ramgarh'     => 'Ramgarh',
			'Sadar'       => 'Sadar',
		),
		'twenty-eight' => array(
			''           => '',
			'Botiaghata' => 'Botiaghata',
			'Dakop'      => 'Dakop',
			'Digholia'   => 'Digholia',
			'Dumuria'    => 'Dumuria',
			'Fultola'    => 'Fultola',
			'Koyra'      => 'Koyra',
			'Paikgasa'   => 'Paikgasa',
			'Rupsha'     => 'Rupsha',
			'Terokhada'  => 'Terokhada',
		),
		'twenty-nine'  => array(
			''                 => '',
			'Austagram'        => 'Austagram',
			'Bajitpur'         => 'Bajitpur',
			'Bhairab'          => 'Bhairab',
			'Hossainpur'       => 'Hossainpur',
			'Itna'             => 'Itna',
			'Karimgonj'        => 'Karimgonj',
			'Katiadi'          => 'Katiadi',
			'Kishoreganjsadar' => 'Kishoreganjsadar',
			'Kuliarchar'       => 'Kuliarchar',
			'Mithamoin'        => 'Mithamoin',
			'Nikli'            => 'Nikli',
			'Pakundia'         => 'Pakundia',
			'Tarail'           => 'Tarail',
		),
		'thirty'       => array(
			''              => '',
			'Bhurungamari'  => 'Bhurungamari',
			'Charrajibpur'  => 'Charrajibpur',
			'Chilmari'      => 'Chilmari',
			'Kurigramsadar' => 'Kurigramsadar',
			'Nageshwari'    => 'Nageshwari',
			'Phulbari'      => 'Phulbari',
			'Rajarhat'      => 'Rajarhat',
			'Rowmari'       => 'Rowmari',
			'Ulipur'        => 'Ulipur',
		),
		'thirty-one'   => array(
			''              => '',
			'Bheramara'     => 'Bheramara',
			'Daulatpur'     => 'Daulatpur',
			'Khoksa'        => 'Khoksa',
			'Kumarkhali'    => 'Kumarkhali',
			'Kushtiasadar'  => 'Kushtiasadar',
			'Mirpurkushtia' => 'Mirpurkushtia',
		),
		'thirty-two'   => array(
			''           => '',
			'Kamalnagar' => 'Kamalnagar',
			'Raipur'     => 'Raipur',
			'Ramganj'    => 'Ramganj',
			'Ramgati'    => 'Ramgati',
			'Sadar'      => 'Sadar',
		),
		'thirty-three' => array(
			''           => '',
			'Aditmari'   => 'Aditmari',
			'Hatibandha' => 'Hatibandha',
			'Kaliganj'   => 'Kaliganj',
			'Patgram'    => 'Patgram',
			'Sadar'      => 'Sadar',
		),
		'thirty-four'  => array(
			''         => '',
			'Kalkini'  => 'Kalkini',
			'Rajoir'   => 'Rajoir',
			'Sadar'    => 'Sadar',
			'Shibchar' => 'Shibchar',
		),
		'thirty-five'  => array(
			''            => '',
			'Magurasadar' => 'Magurasadar',
			'Mohammadpur' => 'Mohammadpur',
			'Shalikha'    => 'Shalikha',
			'Sreepur'     => 'Sreepur',
		),
		'thirty-six'   => array(
			''           => '',
			'Doulatpur'  => 'Doulatpur',
			'Gior'       => 'Gior',
			'Harirampur' => 'Harirampur',
			'Sadar'      => 'Sadar',
			'Saturia'    => 'Saturia',
			'Shibaloy'   => 'Shibaloy',
			'Singiar'    => 'Singiar',
		),
		'thirty-seven' => array(
			''              => '',
			'Gangni'        => 'Gangni',
			'Meherpursadar' => 'Meherpursadar',
			'Mujibnagar'    => 'Mujibnagar',
		),
		'thirty-eight' => array(
			''                 => '',
			'Barlekha'         => 'Barlekha',
			'Juri'             => 'Juri',
			'Kamolganj'        => 'Kamolganj',
			'Kulaura'          => 'Kulaura',
			'Moulvibazarsadar' => 'Moulvibazarsadar',
			'Rajnagar'         => 'Rajnagar',
			'Sreemangal'       => 'Sreemangal',
		),
		'thirty-nine'  => array(
			''            => '',
			'Gajaria'     => 'Gajaria',
			'Louhajanj'   => 'Louhajanj',
			'Sadar'       => 'Sadar',
			'Sirajdikhan' => 'Sirajdikhan',
			'Sreenagar'   => 'Sreenagar',
			'Tongibari'   => 'Tongibari',
		),
		'forty'        => array(
			''                => '',
			'Bhaluka'         => 'Bhaluka',
			'Dhobaura'        => 'Dhobaura',
			'Fulbaria'        => 'Fulbaria',
			'Gafargaon'       => 'Gafargaon',
			'Gouripur'        => 'Gouripur',
			'Haluaghat'       => 'Haluaghat',
			'Iswarganj'       => 'Iswarganj',
			'Muktagacha'      => 'Muktagacha',
			'Mymensinghsadar' => 'Mymensinghsadar',
			'Nandail'         => 'Nandail',
			'Phulpur'         => 'Phulpur',
			'Tarakanda'       => 'Tarakanda',
			'Trishal'         => 'Trishal',
		),
		'forty-one'    => array(
			''             => '',
			'Atrai'        => 'Atrai',
			'Badalgachi'   => 'Badalgachi',
			'Dhamoirhat'   => 'Dhamoirhat',
			'Manda'        => 'Manda',
			'Mohadevpur'   => 'Mohadevpur',
			'Naogaonsadar' => 'Naogaonsadar',
			'Niamatpur'    => 'Niamatpur',
			'Patnitala'    => 'Patnitala',
			'Porsha'       => 'Porsha',
			'Raninagar'    => 'Raninagar',
			'Sapahar'      => 'Sapahar',
		),
		'forty-two'    => array(
			''            => '',
			'Kalia'       => 'Kalia',
			'Lohagara'    => 'Lohagara',
			'Narailsadar' => 'Narailsadar',
		),
		'forty-three'  => array(
			''                 => '',
			'Araihazar'        => 'Araihazar',
			'Bandar'           => 'Bandar',
			'Narayanganjsadar' => 'Narayanganjsadar',
			'Rupganj'          => 'Rupganj',
			'Sonargaon'        => 'Sonargaon',
		),
		'forty-four'   => array(
			''               => '',
			'Belabo'         => 'Belabo',
			'Monohardi'      => 'Monohardi',
			'Narsingdisadar' => 'Narsingdisadar',
			'Palash'         => 'Palash',
			'Raipura'        => 'Raipura',
			'Shibpur'        => 'Shibpur',
		),
		'forty-five'   => array(
			''            => '',
			'Bagatipara'  => 'Bagatipara',
			'Baraigram'   => 'Baraigram',
			'Gurudaspur'  => 'Gurudaspur',
			'Lalpur'      => 'Lalpur',
			'Naldanga'    => 'Naldanga',
			'Natoresadar' => 'Natoresadar',
			'Singra'      => 'Singra',
		),
		'forty-six'    => array(
			''               => '',
			'Atpara'         => 'Atpara',
			'Barhatta'       => 'Barhatta',
			'Durgapur'       => 'Durgapur',
			'Kalmakanda'     => 'Kalmakanda',
			'Kendua'         => 'Kendua',
			'Khaliajuri'     => 'Khaliajuri',
			'Madan'          => 'Madan',
			'Mohongonj'      => 'Mohongonj',
			'Netrokonasadar' => 'Netrokonasadar',
			'Purbadhala'     => 'Purbadhala',
		),
		'forty-seven'  => array(
			''                => '',
			'Dimla'           => 'Dimla',
			'Domar'           => 'Domar',
			'Jaldhaka'        => 'Jaldhaka',
			'Kishorganj'      => 'Kishorganj',
			'Nilphamarisadar' => 'Nilphamarisadar',
			'Syedpur'         => 'Syedpur',
		),
		'forty-eight'  => array(
			''            => '',
			'Begumganj'   => 'Begumganj',
			'Chatkhil'    => 'Chatkhil',
			'Companiganj' => 'Companiganj',
			'Hatia'       => 'Hatia',
			'Kabirhat'    => 'Kabirhat',
			'Sadar'       => 'Sadar',
			'Senbug'      => 'Senbug',
			'Sonaimori'   => 'Sonaimori',
			'Subarnachar' => 'Subarnachar',
		),
		'forty-nine'   => array(
			''           => '',
			'Atghoria'   => 'Atghoria',
			'Bera'       => 'Bera',
			'Bhangura'   => 'Bhangura',
			'Chatmohar'  => 'Chatmohar',
			'Faridpur'   => 'Faridpur',
			'Ishurdi'    => 'Ishurdi',
			'Pabnasadar' => 'Pabnasadar',
			'Santhia'    => 'Santhia',
			'Sujanagar'  => 'Sujanagar',
		),
		'fifty'        => array(
			''                => '',
			'Atwari'          => 'Atwari',
			'Boda'            => 'Boda',
			'Debiganj'        => 'Debiganj',
			'Panchagarhsadar' => 'Panchagarhsadar',
			'Tetulia'         => 'Tetulia',
		),
		'fifty-one'    => array(
			''          => '',
			'Bauphal'   => 'Bauphal',
			'Dashmina'  => 'Dashmina',
			'Dumki'     => 'Dumki',
			'Galachipa' => 'Galachipa',
			'Kalapara'  => 'Kalapara',
			'Mirzaganj' => 'Mirzaganj',
			'Rangabali' => 'Rangabali',
			'Sadar'     => 'Sadar',
		),
		'fifty-two'    => array(
			''          => '',
			'Bhandaria' => 'Bhandaria',
			'Indurkani' => 'Indurkani',
			'Kawkhali'  => 'Kawkhali',
			'Mathbaria' => 'Mathbaria',
			'Nazirpur'  => 'Nazirpur',
			'Nesarabad' => 'Nesarabad',
			'Sadar'     => 'Sadar',
		),
		'fifty-three'  => array(
			''           => '',
			'Baliakandi' => 'Baliakandi',
			'Goalanda'   => 'Goalanda',
			'Kalukhali'  => 'Kalukhali',
			'Pangsa'     => 'Pangsa',
			'Sadar'      => 'Sadar',
		),
		'fifty-four'   => array(
			''         => '',
			'Bagha'    => 'Bagha',
			'Bagmara'  => 'Bagmara',
			'Charghat' => 'Charghat',
			'Durgapur' => 'Durgapur',
			'Godagari' => 'Godagari',
			'Mohonpur' => 'Mohonpur',
			'Paba'     => 'Paba',
			'Puthia'   => 'Puthia',
			'Tanore'   => 'Tanore',
		),
		'fifty-five'   => array(
			''            => '',
			'Baghaichari' => 'Baghaichari',
			'Barkal'      => 'Barkal',
			'Belaichari'  => 'Belaichari',
			'Juraichari'  => 'Juraichari',
			'Kaptai'      => 'Kaptai',
			'Kawkhali'    => 'Kawkhali',
			'Langadu'     => 'Langadu',
			'Naniarchar'  => 'Naniarchar',
			'Rajasthali'  => 'Rajasthali',
			'Sadar'       => 'Sadar',
		),
		'fifty-six'    => array(
			''             => '',
			'Badargonj'    => 'Badargonj',
			'Gangachara'   => 'Gangachara',
			'Kaunia'       => 'Kaunia',
			'Mithapukur'   => 'Mithapukur',
			'Pirgacha'     => 'Pirgacha',
			'Pirgonj'      => 'Pirgonj',
			'Rangpursadar' => 'Rangpursadar',
			'Taragonj'     => 'Taragonj',
		),
		'fifty-seven'  => array(
			''              => '',
			'Assasuni'      => 'Assasuni',
			'Debhata'       => 'Debhata',
			'Kalaroa'       => 'Kalaroa',
			'Kaliganj'      => 'Kaliganj',
			'Satkhirasadar' => 'Satkhirasadar',
			'Shyamnagar'    => 'Shyamnagar',
			'Tala'          => 'Tala',
		),
		'fifty-eight'  => array(
			''           => '',
			'Bhedarganj' => 'Bhedarganj',
			'Damudya'    => 'Damudya',
			'Gosairhat'  => 'Gosairhat',
			'Naria'      => 'Naria',
			'Sadar'      => 'Sadar',
			'Zajira'     => 'Zajira',
		),
		'fifty-nine'   => array(
			''             => '',
			'Jhenaigati'   => 'Jhenaigati',
			'Nalitabari'   => 'Nalitabari',
			'Nokla'        => 'Nokla',
			'Sherpursadar' => 'Sherpursadar',
			'Sreebordi'    => 'Sreebordi',
		),
		'sixty'        => array(
			''               => '',
			'Belkuchi'       => 'Belkuchi',
			'Chauhali'       => 'Chauhali',
			'Kamarkhand'     => 'Kamarkhand',
			'Kazipur'        => 'Kazipur',
			'Raigonj'        => 'Raigonj',
			'Shahjadpur'     => 'Shahjadpur',
			'Sirajganjsadar' => 'Sirajganjsadar',
			'Tarash'         => 'Tarash',
			'Ullapara'       => 'Ullapara',
		),
		'sixty-one'    => array(
			''               => '',
			'Bishwambarpur'  => 'Bishwambarpur',
			'Chhatak'        => 'Chhatak',
			'Derai'          => 'Derai',
			'Dharmapasha'    => 'Dharmapasha',
			'Dowarabazar'    => 'Dowarabazar',
			'Jagannathpur'   => 'Jagannathpur',
			'Jamalganj'      => 'Jamalganj',
			'Sadar'          => 'Sadar',
			'Shalla'         => 'Shalla',
			'Southsunamganj' => 'Southsunamganj',
			'Tahirpur'       => 'Tahirpur',
		),
		'sixty-two'    => array(
			''             => '',
			'Balaganj'     => 'Balaganj',
			'Beanibazar'   => 'Beanibazar',
			'Bishwanath'   => 'Bishwanath',
			'Companiganj'  => 'Companiganj',
			'Dakshinsurma' => 'Dakshinsurma',
			'Fenchuganj'   => 'Fenchuganj',
			'Golapganj'    => 'Golapganj',
			'Gowainghat'   => 'Gowainghat',
			'Jaintiapur'   => 'Jaintiapur',
			'Kanaighat'    => 'Kanaighat',
			'Osmaninagar'  => 'Osmaninagar',
			'Sylhetsadar'  => 'Sylhetsadar',
			'Zakiganj'     => 'Zakiganj',
		),
		'sixty-three'  => array(
			''             => '',
			'Basail'       => 'Basail',
			'Bhuapur'      => 'Bhuapur',
			'Delduar'      => 'Delduar',
			'Dhanbari'     => 'Dhanbari',
			'Ghatail'      => 'Ghatail',
			'Gopalpur'     => 'Gopalpur',
			'Kalihati'     => 'Kalihati',
			'Madhupur'     => 'Madhupur',
			'Mirzapur'     => 'Mirzapur',
			'Nagarpur'     => 'Nagarpur',
			'Sakhipur'     => 'Sakhipur',
			'Tangailsadar' => 'Tangailsadar',
		),
		'sixty-four'   => array(
			''                => '',
			'Baliadangi'      => 'Baliadangi',
			'Haripur'         => 'Haripur',
			'Pirganj'         => 'Pirganj',
			'Ranisankail'     => 'Ranisankail',
			'Thakurgaonsadar' => 'Thakurgaonsadar',
		),
	);
}
